### ISSUE TITLE
Transaction section improvements

### ISSUE THREAD

**Issue by mikev-cw** [RIP-Comm/sossoldi#103]
As discussed on last meeting, here i'm summarize things to do on **transactions** section:

- [x] [list tab] Currently we're showing only last 5 transactions. We need to filter by dates, not by limit
- [x] [list tab] Date picker selection actually does not affects transactions list
- [x] [categories tab] "income" and "Expenses" filter does not change view
- [x] [categories tab] Graph should take colors by category
- [ ] [categories tab] Subcategories shows IDs instead of values when opened
- [x] [categories tab] Subcategories has overflowed text when opened/closed (Fixed on #116)
- [x] [accounts tab] Should be entirely done from scratch
- [x] [all tabs] Collapsible header shows "settembre 2022" when collapsed, regardless on actual month selected (Fixed on #102)

**Comment by lucaantonelli** [comment]
I think this could be closed, everything done in my latest merge.

**Comment by theperu** [comment]
I'll close this one and open a specific issue for the remaining task (*Subcategories shows IDs instead of values when opened*)
