### ISSUE TITLE
Implement weekly build in the CD/CI pipeline

### ISSUE THREAD

**Issue by gallottino** [RIP-Comm/sossoldi#13]

**Comment by matteasu** [comment]
https://blog.gskinner.com/archives/2022/01/flutter-easily-add-ci-testing-with-github-actions.html reference

**Comment by matteasu** [comment]
@bozzelliandrea apparently the action doesn't work, I've tried to remove the "hardcoded" flutter version but it still doesn't work. Can you look into it ?

**Comment by bozzelliandrea** [comment]
@matteasu yep, i'm on it

**Comment by matteasu** [comment]
@bozzelliandrea https://github.com/RIP-Comm/sossoldi/actions/runs/3245749270/jobs/5323709127

**Comment by mikev-cw** [comment]
I'm closing this as it seems has been resolved.
