### ISSUE TITLE
Implement search feature

### ISSUE THREAD

**Issue by theperu** [RIP-Comm/sossoldi#131]
At the moment we have a search icon in the top left of pretty much every screen but it doesn't do anything. For a start I think it would be nice if we could search a specific transaction and see more info about it when we click on it. 
I think that we could leave this feature out of the beta but it would be pretty useful in a 1.0 version of the app.

**Comment by K-w-e** [comment]
Hi @theperu , i would like to contribute.

I wanted to ask about if there is an existing design and additional specifications available for the search functionality.
If you have any specific guidelines or preferences, I would be grateful to learn about them as well.

**Comment by theperu** [comment]
Hi! Welcome to the project 🙂
We haven't discussed the feature a lot but it would be great if a user could search between all the transactions that has ever made by label. 
Another great part would be to have suggestions while you're typing (ex. The first three transactions that are matching what you are currently typing) and when you hit enter then you should see a complete list of all the matching ones. Unfortunately I don't think we have any specific design for it but what I would suggest is to keep it simple for now and use whatever feels easier to you, then when you'll open the PR we will discuss if there is anything that we might want to change. 
Of course if you have specific questions/doubts feel free to comment here or in the discord channel 😁
