### ISSUE TITLE
Currency list not scrolling

### ISSUE THREAD

**Issue by jackrua** [RIP-Comm/sossoldi#137]
In `General Settings`/`Currency`, the `Select a currency` menu doesn't scroll, hence blocking the user from selecting different currencies. 

![p2](https://github.com/RIP-Comm/sossoldi/assets/155536850/bed264fa-4191-4224-afab-3e48c36e4a6b)

This is an easy fix, just change `physics` to `BouncingScrollPhysics()`. If it's ok for you, I can open the PR and take care of it (moreover I can change the name of the function that is misspelled: `sellectCurrency()`).

**Comment by theperu** [comment]
Hi! Thanks for bringing this up! You're more than welcome to come and help so if you want you can open a PR 👍🏻
