### ISSUE TITLE
Dashboard screen

### ISSUE THREAD

**Issue by gallottino** [RIP-Comm/sossoldi#14]
- [x] Graph
- [x] Transaction list
- [x] Budget
- [x] Bottom Menu

**Comment by mikev-cw** [comment]
Update: 
@theperu is working on Graph on #37.
Bottom menu is already done

**Comment by theperu** [comment]
The Graph is now implemented, we still need someone to take a look and fix the transaction list. We also have @antolucanelli that is working on the account list under the graph
