### ISSUE TITLE
Choose the most appropriate icons.

### ISSUE THREAD

**Issue by 0xbaggi** [RIP-Comm/sossoldi#32]
We have to find and implement the most appropriate icons for the pages.

I found a helpful page with a short tutorial of the Icon class and a list of flutter icons (Material Icons): https://api.flutter.dev/flutter/material/Icons-class.html

**Comment by theperu** [comment]
I think that the same icons are listed [here](https://fonts.google.com/icons) and are grouped in categories. Since there are quite a lot of them maybe it will be easier to choose them from there.

**Comment by mikev-cw** [comment]
> I think that the same icons are listed [here](https://fonts.google.com/icons) and are grouped in categories. Since there are quite a lot of them maybe it will be easier to choose them from there.

As discussed on Discord, we're definitely using this icons set!
