### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by mikev-cw** [RIP-Comm/sossoldi#39]
We need an onboarding funnel as seen on [Figma](https://www.figma.com/file/6NyY9yqunpbU7HIkbNEAL3/Sossoldi-App?node-id=1163%3A4030).
Please, if you want to work on this, let us know leaving a comment below!

**Comment by theperu** [comment]
@0xbaggi if I am not mistaken you were working on this, are you still going forward with it? You can post here or on Discord if you have any problem

**Comment by mene412** [comment]
I would like to work on it

**Comment by mikev-cw** [comment]
I'm closing this, since we managed to get the onboarding done on #162
