### ISSUE TITLE
theme data

### ISSUE THREAD

**Issue by mikev-cw** [RIP-Comm/sossoldi#40]
We need re-usable high level class (or anything else) to use same theme colors and fonts across the whole app.
Use our [Figma](https://www.figma.com/file/6NyY9yqunpbU7HIkbNEAL3/Sossoldi-App?node-id=0%3A1) repo to see the UI.
Please, if you want to work on this, let us know leaving a comment below!

**Comment by mikev-cw** [comment]
@GBergatto is writing something related on #36

**Comment by theperu** [comment]
This was covered in one of the latest PR
