### ISSUE TITLE
Internal alerting system

### ISSUE THREAD

**Issue by mikev-cw** [RIP-Comm/sossoldi#44]
We need a class that handles displayable alerts to the user. 
I mean messages like "ok! Your transactions has been added" or error messages like "a category is needed to save the transaction"

**Comment by NandayDev** [comment]
I can do this. Is there UI design to follow, or should I just create a generic alert dialog?

**Comment by mikev-cw** [comment]
Good! I don't think there is a render on Figma about that. 
You can just try to do a generic dialog, with classic success/warning/error/info design.
Thank you!

**Comment by mikev-cw** [comment]
Cool! 
Just fork this repo, do your commits, then open a PR. We'll merge from there.
Thank you!

**Comment by NandayDev** [comment]
There you go https://github.com/RIP-Comm/sossoldi/pull/46
