### ISSUE TITLE
Graphs Page 

### ISSUE THREAD

**Issue by theperu** [RIP-Comm/sossoldi#49]
We need to fill the Graphs page that is currently empty. The best thing I think it is to divide it in three task, one for each widget. Here you can find the [Figma](https://www.figma.com/file/6NyY9yqunpbU7HIkbNEAL3/Sossoldi-App?node-id=976%3A2601&t=0LDo9rqpYWzMm6MJ-0)

- [x] Graph
- [x] Accounts
- [x] Categories

**Comment by theperu** [comment]
Since I have done a little bit of work with the line charts I'll take the upper part of the page. If there are other people that want to take on the rest of the page feel free to comment here

**Comment by napitek** [comment]
I would like to work on it

**Comment by theperu** [comment]
Great! I'll assign this to you then
