### ISSUE TITLE
New Transaction Page

### ISSUE THREAD

**Issue by theperu** [RIP-Comm/sossoldi#50]
We need to redo the work for the New Transaction page because unfortunately what we have now it's different from the [Figma](https://www.figma.com/file/6NyY9yqunpbU7HIkbNEAL3/Sossoldi-App?node-id=1471%3A4126&t=0LDo9rqpYWzMm6MJ-0)

**Comment by lucaantonelli** [comment]
I will take care of it

**Comment by theperu** [comment]
Great, I assigned this feature to you.
