### ISSUE TITLE
Change the upper part of the screen 

### ISSUE THREAD

**Issue by theperu** [RIP-Comm/sossoldi#51]
Currently every screen has "DASHBOARD" written at the top. We need to change it order to have the correct one in all of them (Transaction, Planning, Graph in particular)

**Comment by lucaantonelli** [comment]
I have already did it, tomorrow if i can i will make a PR

**Comment by theperu** [comment]
Great!

**Comment by lucaantonelli** [comment]
It was done in the latest merge. Can be closed.
