### ISSUE TITLE
Currency selector on Settings

### ISSUE THREAD

**Issue by theperu** [RIP-Comm/sossoldi#70]
As discussed in the last call we should add the option to change the currency used in the app.
I think that putting this option is enough and for now I don't think it is necessary to also add it to the Onboarding. We can set the euro as the default and the add the option for the most important for Mr.RIP followers (Dollar, Pound and Swiss Franc).

**Comment by mikev-cw** [comment]
To anyone who will take charge on this: Currencies list should be taken from DB, I'm working on that table.

**Comment by AntonioMiclaus** [comment]
If nobody is working on it, I can start the task.
Currently we have four main categories in the settings page:  Accounts, Categories, Budget, Import/Export.
Should I add one more with general app options? Like this one about the currency used, the light/dark mode, etc.

**Comment by theperu** [comment]
Hi @AntonioMiclaus! How are things going with this issue? This is not to put pressure, we are going to have a meeting in the near future and I would like to understand were we are.

**Comment by theperu** [comment]
Ok, just to clarify at the moment we have a currency selector (settings -> general settings -> currency) but it does nothing when you select a different currency. What we need to implement is a place in which we save the selected currency and always display that instead of the standard "€" that we are doing right now
