### ISSUE TITLE
Refactor Planning page

### ISSUE THREAD

**Issue by theperu** [RIP-Comm/sossoldi#79]
Since the restructure of the DB the current Planning page is not working properly anymore. I'm not 100% sure but I thing last time @0xbaggi worked on it. Not sure on how much work still needs to be done there so if there are more information that would be great for whoever is going to work on this issue.

**Comment by SuperCaliMan** [comment]
I can check it

**Comment by 0xbaggi** [comment]
I'm working on it

**Comment by mikev-cw** [comment]
Merged #107 for frontend. Backend functions needed yet, so i'm keeping this issue open for now

**Comment by theperu** [comment]
@mikev-cw if you agree I would also close this issue since we introduced the budgets with #158 and the recurring payments are covered by #144

**Comment by mikev-cw** [comment]
> @mikev-cw if you agree I would also close this issue since we introduced the budgets with #158 and the recurring payments are covered by #144 

Yeah, go on!
