### ISSUE TITLE
Make the line graphs from dashboard, account modal e graphs page use the real data from the DB

### ISSUE THREAD

**Issue by theperu** [RIP-Comm/sossoldi#89]
Currently we have the line graphs in these 3 section of the app but we are not using them with real data from the DB. The graphs that I am referring to are:
- The main one at the top of the Dashboard ([Figma link](https://www.figma.com/file/6NyY9yqunpbU7HIkbNEAL3/Sossoldi-App?type=design&node-id=870-1075&t=ly7oFThllyoSddw1-4))
- The one displayed when a user taps on of the accounts from the dashboard ([Figma link](https://www.figma.com/file/6NyY9yqunpbU7HIkbNEAL3/Sossoldi-App?type=design&node-id=3014-7173&t=ly7oFThllyoSddw1-4))
- The one at the top of the Graphs page ([Figma link](https://www.figma.com/file/6NyY9yqunpbU7HIkbNEAL3/Sossoldi-App?type=design&node-id=3243-9675&t=ly7oFThllyoSddw1-4))

**Comment by PietroChitto** [comment]
Can I take care of this?

**Comment by theperu** [comment]
Hi! It looks to me that at least the graph on the main page is now working but there are still some things that needs to be addressed. What you could do is make the line graphs on account page e graphs page work, I will assign this issue to you and if you have any question feel free to jump up in the Discord :)

**Comment by PietroChitto** [comment]
Regarding graphic bugs:

- line chart tooltips exit the screen
- find a better  way to display a single point in l;ine chart (now nothing is shown)

Is it possible to open an issue only on the frontend?
