### ISSUE TITLE
Wrong Keyboard when adding a transaction

### ISSUE THREAD

**Issue by mikev-cw** [RIP-Comm/sossoldi#95]
On phisical iPhone 13 Pro, I noticed that the keyboard prompted when you add a new transaction has no comma.

![IMG_B32F0A8BDFA7-1](https://github.com/RIP-Comm/sossoldi/assets/113628339/73393c3b-e475-4e0b-8d5d-6aff989e1ef1)

**Comment by rcasula** [comment]
Hi @lucaantonelli, are you currently working in this? I've the fix ready, I can create a PR of you agree.

**Comment by mikev-cw** [comment]
@rcasula if you have some code ready pull it, don't worry :)
