### ISSUE TITLE
Overflowed text

### ISSUE THREAD

**Issue by mikev-cw** [RIP-Comm/sossoldi#96]
On phisical iPhone 13 Pro, some texts on "settings" and "graphs" pages, is overflowing.
![IMG_3654](https://github.com/RIP-Comm/sossoldi/assets/113628339/7c6b3d84-e4f7-41c5-baa3-7895f01f1a86)
![IMG_3653](https://github.com/RIP-Comm/sossoldi/assets/113628339/02f601b9-4943-4167-8bf4-d80a4f49847e)

**Comment by mikev-cw** [comment]
Graphs page overflow fixed on #110

**Comment by 0xbaggi** [comment]
I think we can close this issue because it has been solved

**Comment by theperu** [comment]
This is also related to the widget in the graphs page, we will close it when the issue #49 will be closed.
