### ISSUE TITLE
not visible text in calendar view

### ISSUE THREAD

**Issue by mikev-cw** [RIP-Comm/sossoldi#97]
In "Transaction" page, when you want to select a time period clicking on the selector, the upper part of the page shows white on light grey text.
![IMG_3656](https://github.com/RIP-Comm/sossoldi/assets/113628339/8d9e9def-a2f1-489d-b8d1-83e983076e5c)

**Comment by GBergatto** [comment]
I've noticed that, on the text version of the date picker, the calendar icon is black, therefore not very visible on the dark blue background.

![Screenshot_20230521_085016.jpg](https://github.com/RIP-Comm/sossoldi/assets/69045457/5449c84c-4a94-4234-b595-ecd206a0062d)

However, I think this might be a bug with Flutter, because that icon stays black regardless of the theme.

**Comment by FedericoBruzzone** [comment]
> I've noticed that, on the text version of the date picker, the calendar icon is black, therefore not very visible on the dark blue background.
> 
> ![Screenshot_20230521_085016.jpg](https://user-images.githubusercontent.com/69045457/239725304-5449c84c-4a94-4234-b595-ecd206a0062d.jpg)
> 
> However, I think this might be a bug with Flutter, because that icon stays black regardless of the theme.

It is not a big deal.
I'll open an issue, ok?

**Comment by FedericoBruzzone** [comment]
> I've noticed that, on the text version of the date picker, the calendar icon is black, therefore not very visible on the dark blue background.
> 
> ![Screenshot_20230521_085016.jpg](https://user-images.githubusercontent.com/69045457/239725304-5449c84c-4a94-4234-b595-ecd206a0062d.jpg)
> 
> However, I think this might be a bug with Flutter, because that icon stays black regardless of the theme.

It's not a big deal.

I would close this issue after your PR merge.
In this case, can you open a new issue?

**Comment by GBergatto** [comment]
Yes I agree. I wouldn't open an issue about it for now. If we find it particularly annoying, we can always address it in the future. I think most people will use the calendar view anyways

**Comment by FedericoBruzzone** [comment]
> Yes I agree. I wouldn't open an issue about it for now. If we find it particularly annoying, we can always address it in the future. I think most people will use the calendar view anyways

All right, no problem! :100:
